// lucide-react の re-export。管理画面で使うアイコンはここから import する
// （ファイルごとに lucide-react を直接 import すると対応表が散らばるため）。
export {
  // ナビ
  LayoutDashboard,
  ClipboardList,
  Trophy,
  ClipboardCheck,
  BookUser,
  Target,
  FileText,
  Receipt,
  MailCheck,
  CalendarDays,
  Users,
  Settings,
  History,
  Snowflake,
  LogOut,
  Globe,
  // サイト管理（src/lib/site-nav.ts）
  LayoutGrid,
  MessageSquareQuote,
  CalendarRange,
  UserRoundCheck,
  Clapperboard,
  Newspaper,
  Handshake,
  Megaphone,
  // 操作
  Search,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Check,
  Plus,
  Minus,
  X,
  ArrowLeft,
  ArrowUpRight,
  ArrowUp,
  ArrowDown,
  Upload,
  Download,
  Mail,
  Send,
  Copy,
  Pencil,
  Trash2,
  Eye,
  EyeOff,
  MoreHorizontal,
  ExternalLink,
  RefreshCw,
  Filter,
  Paperclip,
  FileSpreadsheet,
  FileDown,
  GripVertical,
  Undo2,
  ListPlus,
  PlayCircle,
  PauseCircle,
  Settings2,
  // form-builder の表示専用ブロック（見出し・本文・画像）。
  // Image / Text は DOM のグローバル名と被るので、同名を持つファイルでは *Icon 別名を使う
  Heading,
  HeadingIcon,
  Text,
  TextIcon,
  Image,
  ImageIcon,
  // 状態
  ImageOff,
  Inbox,
  Lock,
  MessageSquare,
  AlertCircle,
  CircleAlert,
  CheckCircle2,
  CircleCheck,
  Info,
  TriangleAlert,
  Loader2,
  Ban,
  Package,
  PackageCheck,
} from "lucide-react";

export type { LucideIcon } from "lucide-react";
